### ISSUE TITLE
Service is not register in Eureka because of Autofac

### ISSUE THREAD

**Issue by xXAvoraXx** [SteeltoeOSS/Steeltoe#1186]
## Describe the bug

I am trying to register my .net 7 web api application to eureka server, but I am getting the following error, why?

Code Explain

I use Autofac for service registrations, I make autofac configurations in a separate dotnet 7 library project. Even though I wrote the necessary configurations to connect to the Eureka service, I get an error.

**Codes:** CoreModule 

```
    using Project.Services.Core.Extensions;
    using Project.Services.Core.Utilities.IoC;
    using Microsoft.Extensions.DependencyInjection;
    using StackExchange.Redis;
    using System.Diagnostics;
    using Serilog;
    using Microsoft.Extensions.Configuration;
    using Steeltoe.Discovery.Client;
    using Steeltoe.Discovery.Eureka;
    
    namespace Project.Services.Core.DependencyResolvers
    {
        public class CoreModule : ICoreModule
        {
            public void Load(IServiceCollection services, IConfiguration configuration)
            {
                services.AddServiceDiscovery(o => o.UseEureka());
    
    
                services.AddMemoryCache();
                services.AddSingleton<ICacheManager, MemoryCacheManager>();
                services.AddSingleton<IDistributedCacheManager, DistributedCacheManager>();
                services.AddHttpContextAccessor();
                services.AddSingleton<Stopwatch>();
    
            }
        }
    }
```

**Program.cs**

```
    builder.Services.AddDependencyResolvers(new ICoreModule[]
                {
                    new CoreModule()
                }, builder.Configuration);
```

**appsettings.json config**

```
      "Spring": {
        "Application": {
          "Name": "STOCK-SERVICE"
        }
      },
      "Eureka": {
        "Client": {
          "ServiceUrl": "http://localhost:867/eureka/",
          "ValidateCertificates": false,
          "ShouldRegisterWithEureka": true
        },
    
        // No docke instance added
        "Instance": {
          //"port": 5004,
          "NonSecurePort": 5004,
          "HostName": "localhost",
          "InstanceId": "Stock.API,Port:5004",
          "StatusPageUrlPath": "/swagger/index.html"
          //"HealthCheckUrlPath": "/api/values/healthcheck"
        }
      }
```

**Error Details**

```
    Autofac.Core.DependencyResolutionException
      HResult=0x80131500
      Message=An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> Steeltoe.Discovery.Client.DiscoveryClientService -> λ:Steeltoe.Discovery.IDiscoveryClient -> λ:Steeltoe.Discovery.Eureka.EurekaDiscoveryClient -> Steeltoe.Discovery.Eureka.EurekaApplicationInfoManager.
      Source=Autofac
      StackTrace:
       at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
       at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
       at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
       at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
       at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
       at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
       at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
       at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
       at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
       at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
       at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
       at Autofac.Core.Resolving.ResolveOperation.InvokePipeline(ResolveRequest request, DefaultResolveRequestContext requestContext)
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
       at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
       at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
       at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
       at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
       at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
       at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
       at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
       at Program.<Main>$(String[] args) 
    
    
    DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptionsMonitor`1[Steeltoe.Discovery.Eureka.EurekaInstanceOptions], Microsoft.Extensions.Logging.ILoggerFactory)' on type 'EurekaApplicationInfoManager'.

    NullReferenceException: Object reference not set to an instance of an object.
```

## Steps to reproduce 
1.
2.

## Environment (please complete the following information):
 - Steeltoe Version: 3.2.4
 - Platform: [e.g. Cloud Foundry, Azure, etc.) 
 - OS: Windows 11
 - .NET Version: 7
 - Any other library versions to note
 - Autofac: 6.4.0

**Comment by xXAvoraXx** [comment]
@TimHess @hananiel

**Comment by TimHess** [comment]
Hi @xXAvoraXx, any chance you can provide a minimal app that reproduces the issue? At a glance, this looks like either the LoggerFactory isn't registered with AutoFac or there is an issue with retrieving the options

**Comment by xXAvoraXx** [comment]
Can you check this repo -> https://github.com/xXAvoraXx/SteeltoeProject

I have prepared a small demo version for you to review.

**Comment by TimHess** [comment]
@xXAvoraXx the project runs fine if you run it directly, it's only when you use docker compose that it fails. This output suggests the issue is that the Core project isn't included in the container:

```
1>#12 [build 4/7] RUN dotnet restore "SteeltoeProject.Services.API.WebAPI/SteeltoeProject.Services.API.WebAPI.csproj"
1>#12 1.246   Determining projects to restore...
1>#12 1.251   Skipping project "/src/src/Services/Common/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core.csproj" because it was not found.
1>#12 1.254   Skipping project "/src/src/Services/Common/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core.csproj" because it was not found.
1>#12 3.709   Restored /src/SteeltoeProject.Services.API.WebAPI/SteeltoeProject.Services.API.WebAPI.csproj (in 2.15 sec).
1>#12 DONE 3.8s
```

**Comment by xXAvoraXx** [comment]
> @xXAvoraXx the project runs fine if you run it directly, it's only when you use docker compose that it fails. This output suggests the issue is that the Core project isn't included in the container:
> 
> ```
> 1>#12 [build 4/7] RUN dotnet restore "SteeltoeProject.Services.API.WebAPI/SteeltoeProject.Services.API.WebAPI.csproj"
> 1>#12 1.246   Determining projects to restore...
> 1>#12 1.251   Skipping project "/src/src/Services/Common/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core.csproj" because it was not found.
> 1>#12 1.254   Skipping project "/src/src/Services/Common/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core/SteeltoeProject.Services.Core.csproj" because it was not found.
> 1>#12 3.709   Restored /src/SteeltoeProject.Services.API.WebAPI/SteeltoeProject.Services.API.WebAPI.csproj (in 2.15 sec).
> 1>#12 DONE 3.8s
> ```

How do I test it without running it in docker-compose? All our projects run on docker-compose, including prod.

**Comment by TimHess** [comment]
You can use `dotnet run` from the context of the api project folder, or (at least for this demo app) use the `http` or `https` profiles defined in launchSettings.json. There should be a dropdown selector on the right side of the start button in Visual Studio that lets you switch between profiles

**Comment by xXAvoraXx** [comment]
> You can use `dotnet run` from the context of the api project folder, or (at least for this demo app) use the `http` or `https` profiles defined in launchSettings.json. There should be a dropdown selector on the right side of the start button in Visual Studio that lets you switch between profiles

Can you check the project again? I placed the "core" project in the Dockerfile.

**Comment by xXAvoraXx** [comment]
The Autofac community was no help in this regard. I need your help. @TimHess

**Comment by TimHess** [comment]
Well, I've identified the issue. The fix is trivial and you can work around it by removing the trailing semicolon on [this line](https://github.com/xXAvoraXx/SteeltoeProject/blob/master/docker-compose.override.yml#L16)

A `NullReferenceException` is thrown on [this line](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Discovery/src/Eureka/EurekaInstanceOptions.cs#L131) because there is an "address" of `null` that comes from [this code](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Discovery/src/ClientBase/ConfigurationUrlHelpers.cs#L22) blindly adding everything from the split operation on the line above.

Thanks for the report! It's unfortunate the way this bug manifested, it really isn't clear why it all fails, but at least it's a simple fix.

**Comment by xXAvoraXx** [comment]
I'm really surprised :) I've been trying for 2 days because of a simple comma, I never thought of it.
