### ISSUE TITLE
Fetch registry Object reference not set EurekaPostConfigurer.UpdateWithDefaultsForRoute

### ISSUE THREAD

**Issue by thnk2wn** [SteeltoeOSS/steeltoe#12]
- Using Steeltoe.Discovery.ClientCore Version "2.2.0" 
- Attempting to fetch registry from a .net core 2.2 console app linux x64 on stack cflinuxfs2

When I attempt to resolve `IDiscoveryClient` type I get the error `Object reference not set to an instance of an object.` error in `Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateWithDefaultsForRoute`. The full call stack follows.

<pre>
2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateWithDefaultsForRoute(EurekaServiceInfo si, EurekaInstanceOptions instOptions)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at System.Lazy`1.CreateValue()
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Steeltoe.Discovery.Eureka.EurekaApplicationInfoManager..ctor(IOptionsMonitor`1 instConfig, ILoggerFactory logFactory)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR --- End of stack trace from previous location where exception was thrown ---
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.<>c.<AddEurekaServices>b__12_0(IServiceProvider p)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at RiverFlowProcessor.Startup.UseDiscoveryClient() in C:\Source\Tools\river-flow-processor\consumer\Startup.cs:line 71
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at RiverFlowProcessor.Startup.Configure() in C:\Source\Tools\river-flow-processor\consumer\Startup.cs:line 45
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at RiverFlowProcessor.Program.Main(String[] args) in C:\Source\Tools\river-flow-processor\consumer\Program.cs:line 23
</pre>

The consumer sample I'm using is at https://github.com/thnk2wn/pcf-river-flow-processor/tree/console-di-svc-reg-use-issue/consumer with [Startup ](https://github.com/thnk2wn/pcf-river-flow-processor/blob/console-di-svc-reg-use-issue/consumer/Startup.cs) and appSettings*.json being the main files of interest (targeting environment Development).

The API side it's attempting to reach is at https://github.com/thnk2wn/pcf-river-flow-processor/tree/console-di-svc-reg-use-issue/api and everything from logging and the Apps Manager service registry dashboard seem to indicate that side is fine.

Using `cf env` on both consumer and API sides both show `p-service-registry` set as expected in `VCAP_SERVICES`.

Locally it seemed to be working okay on the fetch side before but not in my PCF instance.

I've reviewed the samples and tried various things. My use case is slightly different as it is a console app but it is using the built-in DI/IOC like a web app but can't use the webhost specific methods in Steeltoe since it isn't a web app and web references aren't desirable there.

Digging through the code but not quite sure what object is null that it's expecting to be set. 

Questions:

- Ideas to what the problem might be?
- Can the error handling be improved to offer a better indication of what's not set or what the problem might be?

**Comment by TimHess** [comment]
Sorry about the delayed response, this one got lost under a stack of other issues for a while...
@thnk2wn and @dlane771 - Is there still an issue to be addressed here, or was the exception resolved with the PR?

**Comment by thnk2wn** [comment]
@TimHess The PR fixed it for me. I was using my own copy of the assembly and never verified it got pulled into the official NuGet package and worked there but my local version worked in my PCF environment at the time. I'm no longer on the same project or with the same company so I have no way of verifying it anymore.

**Comment by TimHess** [comment]
@thnk2wn thanks for the update ~ I'm going to close this issue for now, we can always re-open it if the issue resurfaces for anybody else :)
