### ISSUE TITLE
ArgumentException from PlaceholderResolverProvider.TryGet

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#1337]
## Describe the bug

For some reason that I don't think is my fault, when I start the latest version of the config sample from Visual Studio and try to reload configuration I get this:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: The value cannot be an empty string. (Parameter 'key')
         at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
         at Steeltoe.Configuration.Placeholder.PlaceholderResolverProvider.TryGet(String key, String& value)
         at Microsoft.Extensions.Configuration.ConfigurationManager.get_Item(String key)
         at Microsoft.Extensions.Configuration.ConfigurationExtensions.AsEnumerable(IConfiguration configuration, Boolean makePathsRelative)+MoveNext()
         at Steeltoe.Management.Endpoint.Refresh.RefreshEndpointHandler.InvokeAsync(Object argument, CancellationToken cancellationToken)
         at Steeltoe.Management.Endpoint.Refresh.RefreshEndpointMiddleware.InvokeEndpointHandlerAsync(HttpContext context, CancellationToken cancellationToken)
         at Steeltoe.Management.Endpoint.Middleware.EndpointMiddleware`2.InvokeAsync(HttpContext context, RequestDelegate next)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

It runs fine from the command line though, so I looked at the response from the env actuator while running in VS and I found what I think is the culprit:
```
":ASPNETCORE_BROWSER_TOOLS": {
    "value": "true"
}
```

## Steps to reproduce
1. Launch the [latest configuration sample](https://github.com/SteeltoeOSS/Samples/tree/latest/Configuration/src) from Visual Studio
2. Click "Refresh Configuration"

## Expected behavior
Operation completes without an exception

## Environment
 - Steeltoe Version 4.0.378-alpha

**Comment by bart-vmware** [comment]
I don't see any harm in changing:
```c#
ArgumentException.ThrowIfNullOrEmpty(key);
```
to:
```c#
ArgumentNullException.ThrowIfNull(key);
```
as apparently, this happens. Should be updated in `PlaceholderResolverProvider`, `EncryptionResolverProvider`, and `RandomValueProvider`.
