### ISSUE TITLE
Serilog DynamicConsole breaks after changing logging levels

### ISSUE THREAD

**Issue by BrockPond** [SteeltoeOSS/steeltoe#135]
I have added SerilogDynamicConsole to the WebHostBuilder along with all the CloudFoundryActuators to the service and middleware levels. Whenever I try to change the logging levels within the UI, then close it and reopen it and try to change the levels again (sometimes I need to change it multiple times), I get this error in the logs in pcf:

2019-10-09T09:42:13.79-0600 [RTR/0] OUT
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT fail: Microsoft.AspNetCore.Server.Kestrel[13]
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT       Connection id "0HLQCPRC3UEEL", Request id "0HLQCPRC3UEEL:0000001E": An unhandled exception was thrown by the application.
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT System.InvalidProgramException: Shouldn't happen
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Extensions.Logging.SerilogDynamicLogger.SerilogDynamicProvider.GetLoggerConfigurations()
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint.GetLoggerConfigurations(IDynamicLoggerProvider provider)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint.DoInvoke(IDynamicLoggerProvider provider, LoggersChangeRequest request)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint.Invoke(LoggersChangeRequest request)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Middleware.EndpointMiddleware`2.HandleRequest(TRequest arg)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Loggers.LoggersEndpointMiddleware.HandleLoggersRequestAsync(HttpContext context)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Loggers.LoggersEndpointMiddleware.Invoke(HttpContext context)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Health.HealthEndpointMiddleware.Invoke(HttpContext context, HealthEndpointCore endpoint)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.Info.InfoEndpointMiddleware.Invoke(HttpContext context)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.CloudFoundry.CloudFoundryEndpointMiddleware.Invoke(HttpContext context)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Steeltoe.Management.Endpoint.CloudFoundry.CloudFoundrySecurityMiddleware.Invoke(HttpContext context)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   2019-10-09T09:42:13.88-0600 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

## Steps to reproduce 
1. Navigate to Logs for a pcf deployed app with logging actuators activated for serilog
2. Click on Configure Logging Levels
3. Change the logging levels on any library (sometimes it takes multiple attempts)
4. Error is thrown and no more no entries in the UI show up in the Configure Logging UI until the app is restarted.

## Expected behavior
The changes should take place and no error should be thrown.  

## Environment (please complete the following information):
 - Platform: Cloud Foundry
 - OS: Linux
 - .NET Core 2.2
 - Steeltoe 2.3.0

## Screenshots
Before changing
![image](https://user-images.githubusercontent.com/7431835/66502654-f1823080-ea82-11e9-9930-8b5d25bb8189.png)

After changing
![image](https://user-images.githubusercontent.com/7431835/66502774-2b533700-ea83-11e9-8679-cfc507175247.png)

Let me know if you need anymore details.

**Comment by hananiel** [comment]
resolved by #138
