### ISSUE TITLE
Beans/Services actuator crash: Your service provider may not support keyed services.

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#1377]
## Describe the bug
While building a .http file for [this new management sample](https://github.com/SteeltoeOSS/Samples/tree/management/Management/src/ActuatorApi), I've hit a case where `/actuator/beans` returns HTTP 500

Unfortunately, I've somehow just lost over an hour's worth of work on the .http file that made this (and every other actuator) super easy to test so I'll have to rebuild that 😭 

## Steps to reproduce
1. Create new minimal API project
2. Add `Steeltoe.Management.Endpoint` @ `4.0.496-alpha`
3. Add `builder.AddAllActuators()`
4. (unknown if relevant) include EF Core & related things
5. set `Management:Endpoints:Actuator:Exposure:Include:0="*"`

## Expected behavior
Actuator returns services that have been registered.

## Additional context or links
```
System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationInstance()
   at Steeltoe.Management.Endpoint.Actuators.Services.ServiceRegistration.GetImplementationType(ServiceDescriptor descriptor)
   at Steeltoe.Management.Endpoint.Actuators.Services.ServiceRegistration..ctor(ServiceDescriptor descriptor)
   at Steeltoe.Management.Endpoint.Actuators.Services.ServicesEndpointHandler.<>c.<ConvertToRegistrations>b__5_0(ServiceDescriptor descriptor)
   at System.Linq.Enumerable.SelectIListIterator`2.Fill(IList`1 source, Span`1 results, Func`2 func)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at Steeltoe.Management.Endpoint.Actuators.Services.ServicesEndpointHandler.ConvertToRegistrations(IServiceCollection services)
   at Steeltoe.Management.Endpoint.Actuators.Services.ServicesEndpointHandler.<>c__DisplayClass4_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at Steeltoe.Management.Endpoint.Actuators.Services.ServicesEndpointHandler.InvokeAsync(Object argument, CancellationToken cancellationToken)
   at Steeltoe.Management.Endpoint.Actuators.Services.ServicesEndpointMiddleware.InvokeEndpointHandlerAsync(HttpContext context, CancellationToken cancellationToken)
   at Steeltoe.Management.Endpoint.Middleware.EndpointMiddleware`2.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by bart-vmware** [comment]
The whole .NET ecosystem is suffering from this, see https://github.com/dotnet/runtime/issues/95789. A [patch](https://github.com/dotnet/runtime/pull/106841) for .NET 8 has recently been merged that returns `null` instead of throwing.
