### ISSUE TITLE
Critical error when starting service using Eureka discovery and setting ASPNETCORE_URLS=http://+:80

### ISSUE THREAD

**Issue by 414004738** [SteeltoeOSS/Steeltoe#483]
## Describe the bug
When an ASP.NET Core service is configured to use Eureka discovery and the ASPNETCORE_URLS environment variable is set to "http://+80", it will fail to start with a Critical error logged:

> crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steeltoe.Discovery.Eureka.EurekaInstanceOptions.ApplyConfigUrls(List`1 addresses, String wildcard_hostname)
   at Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateConfiguration(IConfiguration config, EurekaInstanceOptions options, IApplicationInstanceInfo instanceInfo)
   at Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateConfiguration(IConfiguration config, EurekaServiceInfo si, EurekaInstanceOptions instOptions, IApplicationInstanceInfo appInfo)
   at Steeltoe.Discovery.Eureka.EurekaDiscoveryClientExtension.<>c__DisplayClass9_0.<ConfigureEurekaServices>b__1(EurekaInstanceOptions options)
   at Microsoft.Extensions.Options.PostConfigureOptions`1.PostConfigure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
  ...

Note that the ASPNETCORE_URLS environment variable is set to "http://+:80" by default when using the mcr.microsoft.com/dotnet/core/aspnet:3.1 docker image, which is a common base image used for containerizing ASP.NET Core applications.

The issue appears to be caused by a bug within the ConfigurationUrlHelpers.GetAspNetCoreUrls() method:

```c#
          if (!Uri.TryCreate(uriString, UriKind.Absolute, out result) && (uriString.Contains("*") || uriString.Contains("::") || uriString.Contains("+")))
            Uri.TryCreate(uriString.Replace("*", "---asterisk---").Replace("::", "---asterisk---:").Replace("+", "---asterisk---:"), UriKind.Absolute, out result);
          uriList.Add(result);
```

The '+' character is being replaced with "---asterisk---:" (note ':' character at the end), resulting in an invalid URI string "http://---asterisk---::80". The Uri.TryCreate() method fails and a null value is then added to uriList.

## Steps to reproduce 
1. Configure an ASP.NET Core application to use Steeltoe Eureka Discovery
2. Set the ASPNETCORE_URLS environment variable to "http://+:80"
3. Try to start the service.

## Expected behavior
The service starts without errors.

## Environment (please complete the following information):
 - OS: Mac OSX
 - .NET Version: .NET Core 3.1
 - Steeltoe Version: 3.0.1

**Comment by TimHess** [comment]
Well, I'm not sure how I screwed that up, but thanks for catching it and reporting!
