### ISSUE TITLE
Building Out App With Service Discovery Breaks Using Docker

### ISSUE THREAD

**Issue by TheLazyLemur** [SteeltoeOSS/Steeltoe#529]
## Describe the bug
When I build out my API using dotnet run, everything works as expected. However when I use a Docker container I get a null reference error on startup.

## Steps to reproduce 
1. Create a new Web Api Project
2. Add  ```Steeltoe.Discovery.ClientCore``` ```Steeltoe.Discovery.Consul```
3. Add this to your appsettings.json file
```
  "spring": {
    "application": {
      "name": "AuthService"
    }
  },
  "Consul": {
    "host": "192.168.1.30",
    "port": 8500,
    "discovery": {
      "enabled": true,
      "register": true,
      "scheme": "http",
      "port": "5000",
      "ipAddress": "localhost"
    }
  }
```

4. Run your Consul client
5. Launch the api with dotnet run, all should work as expeced
6. Add a Dockerfile

```
# Build project dlls
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
ENV TZ Africa/Johannesburg
WORKDIR /home
WORKDIR /app
COPY --from=build-env /app/out .
RUN ls -a
CMD ["dotnet", "AuthService.dll"]
```
7. Add a docker-compose.yml
```
version: '3.5'
services:
  jwtservice:
    container_name: jwtservice
    restart: always
    build: ./
    networks:
      - development
    ports:
      - "1448:80"
networks:
  development:
    name: development
    driver: "bridge"
```
8. Launch with docker-compose up and you will see a null reference error (See additional links and context)

## Expected behavior
I expect the app to work the same between Docker and in my Host

## Environment (please complete the following information):
 - Steeltoe 3.1
 - Docker - Linux
 - Linux
 - .NET Version 3.1

## Additional context or links
The error is
```
jwtservice    | Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
jwtservice    |    at Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions.<>c.<ApplyConfigUrls>b__131_0(Uri u)
jwtservice    |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
jwtservice    |    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
jwtservice    |    at Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions.ApplyConfigUrls(List`1 addresses, String wildcard_hostname)
jwtservice    |    at Steeltoe.Discovery.Consul.ConsulDiscoveryClientExtension.<>c__DisplayClass3_0.<ConfigureConsulServices>b__0(ConsulDiscoveryOptions options)
jwtservice    |    at Microsoft.Extensions.Options.PostConfigureOptions`1.PostConfigure(String name, TOptions options)
jwtservice    |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
jwtservice    |    at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
jwtservice    |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
jwtservice    |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
jwtservice    |    at System.Lazy`1.CreateValue()
jwtservice    |    at System.Lazy`1.get_Value()
jwtservice    |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
jwtservice    |    at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
jwtservice    |    at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
jwtservice    |    at Steeltoe.Discovery.Consul.ConsulDiscoveryClientExtension.<>c__DisplayClass4_0.<AddConsulServices>b__1(IServiceProvider p)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
jwtservice    |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
jwtservice    |    at Steeltoe.Discovery.Client.DiscoveryApplicationBuilderExtensions.UseDiscoveryClient(IApplicationBuilder app)
jwtservice    |    at AuthService.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /app/Startup.cs:line 86
jwtservice    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
jwtservice    |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
jwtservice    |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
jwtservice    |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
jwtservice    |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
jwtservice    |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
jwtservice    |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
jwtservice    |    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
jwtservice    | crit: Microsoft.AspNetCore.Hosting.WebHost[6]
jwtservice    |       Application startup exception

```

**Comment by TheLazyLemur** [comment]
This issue is solved by building the production Docker using ``` FROM mcr.microsoft.com/dotnet/core/sdk:3.1 ``` instead of ```FROM mcr.microsoft.com/dotnet/core/aspnet:3.1```. No idea what is causing this?

**Comment by TimHess** [comment]
This exception is being thrown due to a mishandling of the wildcard hostname in the url, which [is already fixed](https://github.com/SteeltoeOSS/Steeltoe/pull/488/files) and will ship in 3.0.2.

That being said, it looks like you've got some configuration for setting ip/port, and that should probably influence whether or not Steeltoe registers the ASP.NET Core url with Consul. We should change something [here](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Discovery/src/Consul/Discovery/ConsulDiscoveryOptions.cs#L236) to take that into consideration
