### ISSUE TITLE
App deployed on Cloud Foundry using UAA server fails authentication intermittently

### ISSUE THREAD

**Issue by tremblaysimon** [SteeltoeOSS/Steeltoe#571]
## Describe the bug
An app deployed on Cloud Foundry using UAA server fails authentication intermittently when that app is using Steeltoe 3.x.x. 

Here is the callstack we get when authentication fails (return a HTTP 401 error).
```
2021-01-06T13:35:20.900-05:00 [APP/PROC/WEB/0] [OUT] info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
2021-01-06T13:35:20.900-05:00 [APP/PROC/WEB/0] [OUT] AuthenticationScheme: Bearer was challenged.
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] Failed to validate the token.
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] System.Threading.Tasks.TaskCanceledException: A task was canceled.
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at Steeltoe.Security.Authentication.CloudFoundry.CloudFoundryTokenKeyResolver.FetchKeySet()
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at Steeltoe.Security.Authentication.CloudFoundry.CloudFoundryTokenKeyResolver.ResolveSigningKey(String token, SecurityToken securityToken, String kid, TokenValidationParameters validationParameters)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
2021-01-06T13:35:21.649-05:00 [APP/PROC/WEB/0] [OUT] at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2021-01-06T13:35:21.653-05:00 [APP/PROC/WEB/0] [OUT] info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
2021-01-06T13:35:21.653-05:00 [APP/PROC/WEB/0] [OUT] Bearer was not authenticated. Failure message: A task was canceled.
2021-01-06T13:35:21.657-05:00 [APP/PROC/WEB/0] [OUT] info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
2021-01-06T13:35:21.657-05:00 [APP/PROC/WEB/0] [OUT] AuthenticationScheme: Bearer was challenged.
```

## Expected behavior
Authentication shouldn't fail intermittently.

## Environment:
 - Steeltoe Version: 3.0.1
 - Platform: Cloud Foundry
 - OS: Linux
 - .NET Version: .NET Core 3.1

**Comment by tremblaysimon** [comment]
It appears that a TaskCanceledException can occur from HttpClient where there is a timeout. Ref.: https://stackoverflow.com/questions/29179848/httpclient-a-task-was-cancelled

In [CloudFoundryTokenKeyResolver.cs](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Security/src/Authentication.CloudFoundryBase/CloudFoundryTokenKeyResolver.cs) there is that timeout:

```csharp
                if (_httpHandler is null)
                {
                    // default HttpClient timeout is 100 seconds
                    _httpClient = HttpClientHelper.GetHttpClient(_validateCertificates, 100);
                }
```

The comment here lies. In reality the timeout is **100 milliseconds** and I think it's why it fails intermittently.

I can submit a pullrequest to fix that.
