### ISSUE TITLE
Startup failure if Kubernetes actuators are enabled

### ISSUE THREAD

**Issue by DaviGia** [SteeltoeOSS/Steeltoe#723]
## Describe the bug

Kubernetes actuators are enabled without checking whether the application is inside Kubernetes or not. This causes the following yaml parse exception at startup when I try to debug the application locally from Visual Studio: 

``` log
   at YamlDotNet.Core.ParserExtensions.Expect[T](IParser parser)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.EnumerableNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize(TextReader input, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at k8s.Yaml.LoadFromString[T](String content)
   at k8s.Yaml.<LoadFromStreamAsync>d__3`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 563
   at k8s.KubernetesClientConfiguration.<LoadKubeConfigAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 563
   at k8s.KubernetesClientConfiguration.<BuildConfigFromConfigFileAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 369
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildDefaultConfig()
   at Steeltoe.Common.Kubernetes.KubernetesClientHelpers.GetKubernetesClient(KubernetesApplicationOptions appInfo, Action`1 kubernetesClientConfiguration, ILogger logger) in /_/src/Common/src/Common.Kubernetes/KubernetesClientHelpers.cs:line 34
   at Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities..ctor(KubernetesApplicationOptions kubernetesApplicationOptions, ILogger logger, IKubernetes kubernetes) in /_/src/Common/src/Common.Kubernetes/StandardPodUtilities.cs:line 30
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 53
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteVisitor.cs:line 49
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 92
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 60
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteVisitor.cs:line 28
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 36
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteVisitor.cs:line 49
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 92
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 60
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteVisitor.cs:line 28
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 134
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteVisitor.cs:line 47
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 92
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 60
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteVisitor.cs:line 28
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 15
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngine.cs:line 92
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngine.cs:line 66
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs:line 58
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs:line 56
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider) in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs:line 79
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider) in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs:line 95
   at Steeltoe.Management.Endpoint.Info.EndpointServiceCollectionExtensions.AddInfoActuator(IServiceCollection services, IConfiguration config) in /_/src/Management/src/EndpointCore/Info/EndpointServiceCollectionExtensions.cs:line 26
   at Steeltoe.Management.Endpoint.ActuatorServiceCollectionExtensions.AddAllActuators(IServiceCollection services, IConfiguration config, MediaTypeVersion version, Action`1 buildCorsPolicy) in /_/src/Management/src/EndpointCore/ActuatorServiceCollectionExtensions.cs:line 73
   at Steeltoe.Management.Kubernetes.ServiceCollectionExtensions.AddKubernetesActuators(IServiceCollection services, IConfiguration config, IPodUtilities podUtilities, MediaTypeVersion version) in /_/src/Management/src/KubernetesCore/ServiceCollectionExtensions.cs:line 63
   at Steeltoe.Management.Kubernetes.HostBuilderExtensions.<>c__DisplayClass2_0.<AddKubernetesActuators>b__1(HostBuilderContext context, IServiceCollection collection) in /_/src/Management/src/KubernetesCore/HostBuilderExtensions.cs:line 44
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider() in /_/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs:line 223
   at Microsoft.Extensions.Hosting.HostBuilder.Build() in /_/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs:line 133
   at Program.Main(String[] args) in Program.cs
```

I've tried to disable kubernetes integration via appsettings.json and envvar (SPRING__CLOUD__KUBERNETES__ENABLED=false) but it does not change the behaviour of the application:

``` json
{
    "spring": {
        "cloud": {
            "kubernetes": {
                "enabled": false
            }
        }
    }
}
```

## Steps to reproduce

1. Create a basic aspnetcore microservice
2. Add Steeltoe Kubernetes package, my project has the following packages enabled:
 ``` xml
<PackageReference Include="Steeltoe.Bootstrap.Autoconfig" Version="3.1.0" />
<PackageReference Include="Steeltoe.Discovery.ClientCore" Version="3.1.0" />
<PackageReference Include="Steeltoe.Discovery.Kubernetes" Version="3.1.0" />
<PackageReference Include="Steeltoe.Extensions.Configuration.KubernetesCore" Version="3.1.0" />
<PackageReference Include="Steeltoe.Management.EndpointBase" Version="3.1.0" />
<PackageReference Include="Steeltoe.Management.EndpointCore" Version="3.1.0" />
<PackageReference Include="Steeltoe.Management.KubernetesCore" Version="3.1.0" />
```
3. Configure startup to use Autoconfig:
``` cs
public static IHostBuilder CreateHostBuilder(string[] args)
{
    var builder = Host.CreateDefaultBuilder(args);

    //create initialization logger factory(allow steeltoe components that runs during host initialization to log)
    var initLoggerFactory = new LoggerFactory().AddSerilog(new LoggerConfiguration()
        .MinimumLevel.Error().WriteTo.Console().CreateLogger());

    return builder
        //.AddKubernetesConfiguration(null, initLoggerFactory) //alternative that still does not work
        .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
        .AddSteeltoe(loggerFactory: initLoggerFactory);
}
```

## Expected behavior
The application should not try to perform any request to `kube-apiserver` component if the environment is not Kubernetes. Moreover the application should not execute any Kuberentes related operation if `spring:cloud:kubernetes:enabled` is false.

## Environment (please complete the following information):
 - Steeltoe Version 3.1.0
 - OS: Windows (Docker Desktop installed with Kubernetes cluster disabled)
 - .NET Core 3.1.0

**Comment by TimHess** [comment]
Thanks for the report, but I'm not seeing that behavior with [this app I just made](https://github.com/SteeltoeOSS/Samples/tree/k8sManagement/Management/src/Kubernetes) or [this pre-existing sample](https://github.com/SteeltoeOSS/Samples/tree/main/Configuration/src/Kubernetes) though - am I missing something?

**Comment by DaviGia** [comment]
I'll investigate and let you know.

**Comment by DaviGia** [comment]
@TimHess,

I've tried your sample and the result is the same. I'm not able to debug KubernetesClient library because no debug symbols are available. Have you managed to debug it correctly? I've noticed the current used version is 2.0.16, and it seems pretty old [5.0.13](https://www.nuget.org/packages/KubernetesClient/).

The exception is throw by `KubernetesClientConfiguration.BuildDefaultConfig();` call from here:

https://github.com/SteeltoeOSS/Steeltoe/blob/af4d8f3f80e80791385d740878f7ca8344152d0b/src/Common/src/Common.Kubernetes/KubernetesClientHelpers.cs#L21-L45

**Comment by TimHess** [comment]
@DaviGia last I checked you could upgrade `KubernetesClient` by adding a direct reference in your project file and it worked up to v4.something... I'm still not seeing this exception even with making changes there, although I am getting the following with both v4 and v5:

```
Steeltoe.Management.Endpoint.Info.InfoEndpoint: Error: Exception: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.HttpOperationResponse`1<k8s.Models.V1PodList>> k8s.IKubernetes.ListNamespacedPodWithHttpMessagesAsync(System.String, System.Nullable`1<Boolean>, System.String, System.String, System.String, System.Nullable`1<Int32>, System.String, System.Nullable`1<Int32>, System.Nullable`1<Boolean>, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.String>>, System.Threading.CancellationToken)'.
   at Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync()
   at Steeltoe.Management.Kubernetes.KubernetesInfoContributor.Contribute(IInfoBuilder builder)
   at Steeltoe.Management.Endpoint.Info.InfoEndpoint.BuildInfo(IList`1 infoContributors)
```

So it's probably time to upgrade the kubernetesclient reference anyway, but that will have a some ripple effect as it requires netstandard2.1 and several Steeltoe projects that use it are still on netstandard2.1. I'll log a separate issue for that.

I also have a `.kube\config`, all that is in it is my docker desktop config, but I currently have that k8s off so I'd expect to be seeing the same failures.

**Comment by DaviGia** [comment]
@TimHess,
I haven't enabled docker-desktop kubernetes cluster. My kubeconfig points to clusters on other machines. Which version of kubectl do you have? Can you provide you kubeconfig file so I can compare (removing sensible data of course).
In any case I think that there is still a bug, because Kubernetes code should not be hit if the environment is not Kubernetes (don't know why KubernetesClient tries to read the local kubeconfig... it doesn't seems such a good idea to me). In other situation Steeltoe skips Kubernetes integration by checking whether `Platform.IsKubernetes()` (e.g. [bootstrap](https://github.com/SteeltoeOSS/Steeltoe/blob/5356b0b0204bd5199d3844bec83237c57decf1d4/src/Bootstrap/src/Autoconfig/WebHostBuilderExtensions.cs#L104)). So I think Kubernetes actuators should do that too. What do you think?

**Comment by TimHess** [comment]
@DaviGia I'm pretty sure the k8s info contributer is supposed to use that check internally, and handle non-k8s env. I know I was seeing a value in the response that it knew it wasn't running in k8s, and I got different results when I re-enabled the local cluster.  I confirmed that the address in the config file was not valid during testing (connection refused), I guess docker desktop just doesn't cleanup the connect when you remove it.

I'm traveling for the next several days though, so I won't be able to look at this more until Tuesday

**Comment by TimHess** [comment]
@DaviGia  Reading local config is a fallback if no kubeconfig path has been provided at `Spring:Cloud:Kubernetes:Config:Paths`, do you have another idea how this should work?

I think that check in bootstrap is because the config providers don't seem to be able to survive a connection refused event on startup if the config provider is enabled.

I wasn't completely correct about the info contributor code though, it is built to handle connection failures rather than enable/disable based on k8s detection though so it shouldn't be what's breaking. We could consider making changes here, but at least part of the intent for this contributor was to return k8s info if possible even if not actually running on k8s.

I'm still unable to duplicate the issue. Given that there yaml parsing details in the stack trace maybe there's an issue with your config file?

My kubectl version is 1.21.2, this is my kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <data>
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```

**Comment by DaviGia** [comment]
> Reading local config is a fallback if no kubeconfig path has been provided

I cannot understand why you should fallback to this. A container running inside k8s does not have access to kubeconfig. I think that this should not be a fallback and it should not be enabled by default. If the application is not running inside a k8s cluster it should not report any k8s information IMO. I'm not sure if I'm missing something or not.

> Given that there yaml parsing details in the stack trace maybe there's an issue with your config file?

I checked and the file structure is the same, the only difference is that I don't have docker-desktop context, but other context that points to microk8s remote clusters. I checked for invalid characters like tabulation but I cannot find any.

**Comment by TimHess** [comment]
Sorry, my description of setting the default configuration was incomplete.  As seen in one of the code snippets you posted above, if `Paths` is set, Steeltoe uses that to set the env var `KUBECONFIG`. Then we call `KubernetesClientConfiguration.BuildDefaultConfig()` which does this:
```
        // Summary:
        //     Initializes a new instance of the k8s.KubernetesClientConfiguration from default
        //     locations If the KUBECONFIG environment variable is set, then that will be used.
        //     Next, it looks for a config file at k8s.KubernetesClientConfiguration.KubeConfigDefaultLocation.
        //     Then, it checks whether it is executing inside a cluster and will use k8s.KubernetesClientConfiguration.InClusterConfig.
        //     Finally, if nothing else exists, it creates a default config with localhost:8080
        //     as host.
        //
        // Returns:
        //     Instance of thek8s.KubernetesClientConfiguration class
        //
        // Remarks:
        //     If multiple kubeconfig files are specified in the KUBECONFIG environment variable,
        //     merges the files, where first occurrence wins. See https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files.
```

I'll see if I can get the kubernetesclient reference updated today and hopefully that will resolve the issue

**Comment by TimHess** [comment]
@DaviGia are you able to try out the updated package from [the dev feed](https://pkgs.dev.azure.com/dotnet/Steeltoe/_packaging/dev/nuget/v3/index.json)? the k8s client upgrade should be included in 3.1.1-6252 and higher.

**Comment by DaviGia** [comment]
@TimHess, I can confirm that with all Steeltoe's packages updated to version 3.1.1-6308 the yaml parsing exception is gone and the application startup is completed without errors.

**Comment by TimHess** [comment]
@DaviGia thanks again for the report and working with me to make sure this issue was resolved
