### ISSUE TITLE
DbMigrations Endpoint NullReference

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#741]
I'm probably hitting this because the app doesn't have any Entity Framework db contexts, so it's fine if this endpoint doesn't really work in that scenario, but this exception should be caught and handled differently:
```
An unhandled exception has occurred while executing the request.
System.TypeInitializationException: The type initializer for 'Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpoint' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpoint..cctor()
   --- End of inner exception stack trace ---
   at Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpoint.<>c.<DoInvoke>b__13_1(TypeInfo type)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpoint.DoInvoke()
   at Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpoint.Invoke()
   at Steeltoe.Management.Endpoint.Middleware.EndpointMiddleware`1.HandleRequest()
   at Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpointMiddleware.HandleEntityFrameworkRequestAsync(HttpContext context)
   at Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Probably happening on line 95 of DbMigrationsEndpoint.cs

**Comment by kenswan** [comment]
Tried debugging this issue, but I was unable to reproduce (see log output below).  I tried registering in host builder with `.AddDbMigrationsActuator` and also tried in service container with `.AddDbMigrationsActuator` with endpoint routing `.Map<DbMigrationsEndpoint>()`. 

Please let me know if there was any additional setup involved that may help reproduce.

Logs: 
`dbug: Steeltoe.Management.Endpoint.DbMigrations.DbMigrationsEndpointMiddleware[0]
      endpoint: dbmigrations, contextPath: /actuator, enabled: True, exposed: False`

**Comment by TimHess** [comment]
I guessed the right file, but wrong line, this throws on [line 39](https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Management/src/EndpointBase/DbMigrations/DbMigrationsEndpoint.cs#L39).

I hit this exception using Autoconfig with all endpoints exposed and without any references to EF. Turns out to be a reflection issue
