### ISSUE TITLE
Unhandled exception with IDiscoveryClient in PCF with dotnet buildpack

### ISSUE THREAD

**Issue by Tandis5** [SteeltoeOSS/Steeltoe#872]
We are currently in the process of upgrading our applications to .NET 6.  Some of these applications are APIs and some are background services.  The APIs are working fine with service discovery (Eureka to be exact) in PCF, but the background services are not.  We are getting an exception when it tries to instantiate an IDiscoveryClient.  I will post the exception at the end.

However, this ONLY happens in PCF when the app is pushed with the dotnet buildpack.  If I setup the VCAP_SERVICES and VCAP_APPLICATION environment variables locally on my development PC and run the app, it will connect to the discovery service (and configuration service) just fine and the app runs.  If I publish the app self-contained with a runtime of linux-x64 and push to PCF with the binary buildpack, the app will run just fine.  It's only when building for any runtime and pushing with the dotnet buildpack that I get the exception.  And if I create a minimal API that does basically the same thing in the startup, it works just fine.

I have created a minimal sample repo to show how to cause the exception.
[Sample Repo](https://github.com/Tandis5/TestEureka)

We are currently using dotnet buildpack version 2.3.43.  I do not know the Eureka version as that is just the tile in PCF and I don't see any way to get the version number from that (I can request that from our platform team if you need it).

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Any[TSource](IEnumerable\`1 source)
at Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateWithDefaultsForRoute(EurekaServiceInfo si, EurekaInstanceOptions instOptions)
at Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateConfiguration(IConfiguration config, EurekaServiceInfo si, EurekaInstanceOptions instOptions, IApplicationInstanceInfo appInfo)
at Steeltoe.Discovery.Eureka.EurekaDiscoveryClientExtension.<ConfigureEurekaServices>b__10_3(EurekaInstanceOptions options, IServiceProvider serviceProvider)
at Microsoft.Extensions.Options.PostConfigureOptions\`2.PostConfigure(String name, TOptions options)
at Microsoft.Extensions.Options.OptionsFactory\`1.Create(String name)
at Microsoft.Extensions.Options.OptionsMonitor\`1.<>c__DisplayClass10_0.<Get>b__0()
at System.Lazy\`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy\`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy\`1.CreateValue()
at System.Lazy\`1.get_Value()
at Microsoft.Extensions.Options.OptionsCache\`1.GetOrAdd(String name, Func\`1 createOptions)
at Microsoft.Extensions.Options.OptionsMonitor\`1.Get(String name)
at Microsoft.Extensions.Options.OptionsMonitor\`1.get_CurrentValue()
at Steeltoe.Discovery.Eureka.EurekaApplicationInfoManager.get_InstanceConfig()
at Steeltoe.Discovery.Eureka.EurekaApplicationInfoManager..ctor(IOptionsMonitor\`1 instConfig, ILoggerFactory logFactory)
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span\`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
at System.Collections.Concurrent.ConcurrentDictionary\`2.GetOrAdd(TKey key, Func\`2 valueFactory)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
at lambda_method1(Closure , IServiceProvider , Object[] )
at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory\`1.CreateClient(HttpClient httpClient)
at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TClient](IServiceProvider s, IHttpClientBuilder builder)
at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass10_0\`1.<AddTypedClientCore>b__0(IServiceProvider s)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Steeltoe.Discovery.Eureka.EurekaDiscoveryClientExtension.<>c.<AddEurekaServices>b__11_0(IServiceProvider p)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
at System.Collections.Concurrent.ConcurrentDictionary\`2.GetOrAdd(TKey key, Func\`2 valueFactory)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Program.\<Main\>$(String[] args) in TestEureka\Program.cs:line 90
at Program.\<Main\>(String[] args)
```

**Comment by TimHess** [comment]
Hi @Tandis5,

Thanks for reporting this issue. At first glance, it seems likely to be [this line](https://github.com/SteeltoeOSS/Steeltoe/blob/d9fbd2ff16d2e22f5b72c56c63790e3632fe4893/src/Discovery/src/Eureka/EurekaPostConfigurer.cs#L198) causing the issue. We'll have to dig into it a little more to confirm this is the issue and get to a resolution, but in the meantime, could you try adding a route to the application as a workaround?

**Comment by Tandis5** [comment]
Thanks Tim!  That worked.  We will use that workaround until you have a fix in!
