### ISSUE TITLE
Error being shown when deploying to Gov.uk PaaS using steeltoe

### ISSUE THREAD

**Issue by Mark-Baxter** [SteeltoeOSS/Steeltoe#896]
Hi

I'm currently getting an error when trying to deploy to Gov.uk PaaS using cloud foundry and steeltoe to get the MySql db details from the VCAP services. I'm currently in the process of migrating the app from .netcore 3.1 to .net 6 and testing that it still works.

The environment details are:
PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.7" 
PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.7"
PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.7"
PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" 
PackageReference Include="Steeltoe.CloudFoundry.Connector.EFCore" Version="2.5.5" 
PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.5.5" 
PackageReference Include="Steeltoe.Common.Hosting" Version="3.2.0" 

The error message I'm getting is:
   2022-07-26T16:04:27.23+0100 [APP/PROC/WEB/0] ERR Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
   2022-07-26T16:04:27.23+0100 [APP/PROC/WEB/0] ERR Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null'.
   2022-07-26T16:04:27.23+0100 [APP/PROC/WEB/0] ERR Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null'.
   2022-07-26T16:04:27.23+0100 [APP/PROC/WEB/0] ERR Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null'.
   2022-07-26T16:04:27.23+0100 [APP/PROC/WEB/0] ERR Could not load type 'Steeltoe.Common.HealthChecks.IHealthContributor' from assembly 'Steeltoe.Common, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null'.

Are Steeltoe.CloudFoundry.Connector.EFCore and Steeltoe.CloudFoundry.ConnectorCore compatible with .Net 6?

I've attached the program and startup files in case they provide any useful insight
[Program.txt](https://github.com/SteeltoeOSS/Steeltoe/files/9197229/Program.txt)
[Startup.txt](https://github.com/SteeltoeOSS/Steeltoe/files/9197230/Startup.txt)

Thanks in advance for your time,
Mark

**Comment by hananiel** [comment]
Hi Mark,
Looks like you have different Steeltoe dependencies at different versions. Can you try updating all of them. 
    Yes .NET6 is supported. If you still have issues can you attach a minimal project and I will take a look. 
Thanks 
Hananiel

**Comment by TimHess** [comment]
Specifically, these:
```
PackageReference Include="Steeltoe.CloudFoundry.Connector.EFCore" Version="2.5.5"
PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.5.5"
```
should be replaced with:
```
PackageReference Include="Steeltoe.Connector.EFCore" Version="3.2.0"
PackageReference Include="Steeltoe.Connector.ConnectorCore" Version="3.2.0"
PackageReference Include="Steeltoe.Connector.CloudFoundry" Version="3.2.0"
```

**Comment by Mark-Baxter** [comment]
Hi folks. thanks for taking the time to respond. 

I've made those changes and wondering about the lines below in the program.cs

public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseCloudHosting()
                _.AddCloudFoundry()_
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

Is there a replacement for .AddCloudFoundry() in the new packages? I'm getting the error message below when I try to do the deploy without that line.

   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR ---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 433
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 915
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 406
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   2022-07-27T14:38:46.72+0100 [APP/PROC/WEB/0] ERR --- End of inner exception stack trace ---

**Comment by TimHess** [comment]
I'm pretty sure that should be `.AddCloudFoundryConfiguration()` (as of 3.0 I think) and coming from `Steeltoe.Extensions.Configuration.CloudFoundryCore`

**Comment by Mark-Baxter** [comment]
Hi Tim, got it deployed and tested successfully. Thanks for the help! :)
