### ISSUE TITLE
SCS 3.0 config server is not working with Steeltoe libs

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/steeltoe#92]
Error when binding app to SCS 3.x config server:
`2019-08-02T09:39:31.688-05:00` [CELL/0] [OUT] Starting health monitoring of container

2019-08-02T09:39:33.807-05:00 [APP/PROC/WEB/0] [OUT] info: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]

2019-08-02T09:39:33.807-05:00 [APP/PROC/WEB/0] [OUT] Fetching config from server at: http://localhost:8888

2019-08-02T09:39:36.515-05:00 [APP/PROC/WEB/0] [OUT] fail: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]

2019-08-02T09:39:36.515-05:00 [APP/PROC/WEB/0] [OUT] Config Server exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888

2019-08-02T09:39:36.515-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)

2019-08-02T09:39:36.515-05:00 [APP/PROC/WEB/0] [OUT] at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
`

**Comment by jkonicki** [comment]
One issue:

This line https://github.com/SteeltoeOSS/steeltoe/blob/57d40928467a2b59b00104d207ed34373f764260/src/Configuration/src/ConfigServerBase/ConfigurationSettingsHelper.cs#L24 seems to expect that the config server will be in a section under VCAP_SERVICES called `p-config-server`

However, in v3, the config server is called `p.config-server`.
